package com.kie_pract.incentivetest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IncentiveTest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private long payment;

	private java.lang.String type_of;

	private java.lang.String based_on;

	private java.lang.String results;

	private java.lang.String sales_type;

	private int scheme_id;

	private boolean ps;

	private java.lang.String eligibility_to;

	private java.lang.String eligibility_to_2;

	private java.lang.String type_of_2;

	private java.lang.String based_on_2;

	private double incentiveforPrimaryP;

	private double incentiveforSecondaryP;

	public IncentiveTest() {
	}

	public java.lang.String getType_of() {
		return this.type_of;
	}

	public void setType_of(java.lang.String type_of) {
		this.type_of = type_of;
	}

	public java.lang.String getBased_on() {
		return this.based_on;
	}

	public void setBased_on(java.lang.String based_on) {
		this.based_on = based_on;
	}

	public java.lang.String getResults() {
		return this.results;
	}

	public void setResults(java.lang.String results) {
		this.results = results;
	}

	public long getPayment() {
		return this.payment;
	}

	public void setPayment(long payment) {
		this.payment = payment;
	}

	public java.lang.String getSales_type() {
		return this.sales_type;
	}

	public void setSales_type(java.lang.String sales_type) {
		this.sales_type = sales_type;
	}

	public int getScheme_id() {
		return this.scheme_id;
	}

	public void setScheme_id(int scheme_id) {
		this.scheme_id = scheme_id;
	}

	public java.lang.String getEligibility_to() {
		return this.eligibility_to;
	}

	public void setEligibility_to(java.lang.String eligibility_to) {
		this.eligibility_to = eligibility_to;
	}

	public java.lang.String getEligibility_to_2() {
		return this.eligibility_to_2;
	}

	public void setEligibility_to_2(java.lang.String eligibility_to_2) {
		this.eligibility_to_2 = eligibility_to_2;
	}

	public java.lang.String getType_of_2() {
		return this.type_of_2;
	}

	public void setType_of_2(java.lang.String type_of_2) {
		this.type_of_2 = type_of_2;
	}

	public java.lang.String getBased_on_2() {
		return this.based_on_2;
	}

	public void setBased_on_2(java.lang.String based_on_2) {
		this.based_on_2 = based_on_2;
	}

	public double getIncentiveforPrimaryP() {
		return this.incentiveforPrimaryP;
	}

	public void setIncentiveforPrimaryP(double incentiveforPrimaryP) {
		this.incentiveforPrimaryP = incentiveforPrimaryP;
	}

	public double getIncentiveforSecondaryP() {
		return this.incentiveforSecondaryP;
	}

	public void setIncentiveforSecondaryP(double incentiveforSecondaryP) {
		this.incentiveforSecondaryP = incentiveforSecondaryP;
	}

	public boolean isPs() {
		return this.ps;
	}

	public void setPs(boolean ps) {
		this.ps = ps;
	}

	public IncentiveTest(long payment, java.lang.String type_of,
			java.lang.String based_on, java.lang.String results,
			java.lang.String sales_type, int scheme_id, boolean ps,
			java.lang.String eligibility_to, java.lang.String eligibility_to_2,
			java.lang.String type_of_2, java.lang.String based_on_2,
			double incentiveforPrimaryP, double incentiveforSecondaryP) {
		this.payment = payment;
		this.type_of = type_of;
		this.based_on = based_on;
		this.results = results;
		this.sales_type = sales_type;
		this.scheme_id = scheme_id;
		this.ps = ps;
		this.eligibility_to = eligibility_to;
		this.eligibility_to_2 = eligibility_to_2;
		this.type_of_2 = type_of_2;
		this.based_on_2 = based_on_2;
		this.incentiveforPrimaryP = incentiveforPrimaryP;
		this.incentiveforSecondaryP = incentiveforSecondaryP;
	}

}